#!/bin/sh

if [ -z "$1" ]; then
  TB=/home/pont/progs/thunderbird/thunderbird
else
  TB="$1"
fi

while true; do make && cp chrome/kbdmover.jar /home/pont/.mozilla-thunderbird/inobnp66.default/extensions/\{191E67F6-A6CF-11D9-8BDE-F66BAD1E3F3A\}/chrome/kbdmover.jar && cp chrome/kbdmover.jar  /home/pont/.thunderbird/c00psj4e.Pontus/extensions/\{191E67F6-A6CF-11D9-8BDE-F66BAD1E3F3A\}/chrome/kbdmover.jar && (sleep 2; $TB) done
